site_name: 𝔜𝔄𝔉𝔄 𝔪𝔞𝔯𝔨𝔱 # Change this to your site name
site_url: # Change this to your site URL
site_description: "yafa markt, 雅法"
site_author: scillidan
copyright: Copyright © 2023 scillidan
# docs_dir: .
# site_dir: ../site
# repo_name: YAFA-site
# repo_url: https://github.com/scillidan/YAFA-site

theme:
    name: material
    logo: assets/favicon.png
    favicon: assets/favicon.png
    # custom_dir: overrides
    language: en
    # font: false
    icon:
      # admonition:
      #   note: material/pin
      repo: fontawesome/brands/git-alt
      view: material/eye
    palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    features:
        - navigation.indexes
        - navigation.prune
        - navigation.tracking
        - navigation.tabs
        - navigation.instant
        - navigation.sections
        - navigation.top
        # - navigation.tabs.sticky
        # - navigation.expand
        - content.tooltips
        - content.tabs.link
        - content.code.copy
        - search.suggest
        - search.highlight
markdown_extensions:
  - callouts
  - mdx_truly_sane_lists:
      nested_indent: 4
  - mdx_breakless_lists
  # - sane_lists
  # - markdown_captions
  - footnotes
  - attr_list
  - meta
  - smarty
  - tables
  - def_list
  - admonition
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tasklist:
       custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      # auto_append: ["assets/css/extra.css"]
      base_path: ["docs"]
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - minify_html
  # - heti:
  #     disable_serve: false
  - meta-manager
  - meta-descriptions
  - git-revision-date-localized:
      locale: en
      type: iso_date
      enable_creation_date: true
      fallback_to_build_date: true
      exclude:
        - index.md
        - blog/deploy-sites-to-vps.md
        - blog/deploy-sites-to-vps-expand.md
        - blog/make-la.isla.minima.2014.srt.ass.md
  # - footermatter
  - autolinks
  - open-in-new-tab
  - glightbox:
      auto_caption: true
      caption_position: bottom
      skip_classes:
        - skip-lightbox
  # - resize-images:
  #     source-dir: assets/media
  #     target-dir: assets/media-min
  #     enable_cache: True
  #     size: [800, 600]
  #     extensions: ['.jpg', '.jpeg', '.png', '.gif', '.svg']
  - mkdocs-video:
      is_video: True
      video_muted: True
      video_controls: True
      css_style:
        width: "100%"
  - table-reader
  - literate-nav:
      nav_file: SUMMARY.md
  # - tags:
  #     tags_slugify: !!python/object/apply:pymdownx.slugs.slugify
  #       kwds:
  #         case: lower
  #     tags_slugify_separator: "-"
  #     tags_file: Note/index.md
  # - autotag:
  #     globs:
  #       "Blog/**": Blog
  #       "Note/**": Note
  #     regex:
  #       "([^/]+)/([^/]+)/.*":
  #       # - "{0}"
  #       - "{1}/"
  #       # - "{0}/{1}/"
  - search
  - exclude-search:
      exclude:
        - docs/.htaccess
        - docs/robots.txt
      # ignore:
      #   - dir/second.md#some-heading
      exclude_unreferenced: true
  - exclude:
      glob:
        - "*.pdf"
        - ".obsidian"
      # regex:
      #   - '.*\.(tmp|bin|tar|.obsidian)$'
  # - furigan:
  #     multiple: "§"
  #     inicio: "【"
  #     fin: "】"
  # - monorepo
  # - multirepo:mkdo
  #     cleanup: true
  #     keep_docs_dir: true
  #     repos:
  #       - section: "Readme-page"
  #         section_path: Readme
  #         import_url: "https://github.com/scillidan/README-page?branch=main"
  # - same-dir
  # - awesome-pages
  # - pagenav-generator
  # - blog:
  #     blog_dir: .
  #     blog_toc: true
  #     post_date_format: short
  #     post_url_format: "{slug}"
  #     archive_date_format: yyyy
  # - mkdocs/exporter
  # - mkdocs/exporter/pdf:
  #     concurrency: 8
  #     covers:
  #       front: D:/cacher/mkdocs_exporter/resources/templates/covers/front.html.j2
  #       back: D:/cacher/mkdocs_exporter/resources/templates/covers/back.html.j2
  #     stylesheets:
  #       - D:/cacher/mkdocs_exporter/resources/stylesheets/pdf.scss
  # - mkdocs/exporter/extras:
  #     buttons:
  #       - title: Download as PDF
  #         enabled: !!python/name:mkdocs_exporter.plugins.pdf.button.enabled
  #         icon: !!python/name:mkdocs_exporter.plugins.pdf.button.icon
  #         attributes:
  #           href: !!python/name:mkdocs_exporter.plugins.pdf.button.href
  #           download: !!python/name:mkdocs_exporter.plugins.pdf.button.download
  # - heti:
  #     disable_serve: false
extra_css:
  - assets/css/extra.css
  # - assets/css/customization.css
  - assets/css/admonition.css
  # - assets/css/furigana.css
# extra_javascript:
#   - assets/javascripts/extra.js
# nav:
  # - Version:
  #   - v1: '*include /*/mkdocs.yml'
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/scillidan/YAFA-site
      name: YAFA-site
    - icon: fontawesome/brands/creative-commons-by
      link: https://creativecommons.org/licenses/by/4.0/
      name: CC BY 4.0