name: mkdocs
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material
      - run: pip install mdx-breakless-lists mdx_truly_sane_lists mkdocs-audio mkdocs-autolinks-plugin mkdocs-document-dates mkdocs-exclude mkdocs-exclude-search mkdocs-glightbox mkdocs-literate-nav mkdocs-llmstxt mkdocs-minify-plugin mkdocs-open-in-new-tab mkdocs-video
      - run: mkdocs gh-deploy --force
